version: '2'
services:
    jhispter4mono-app:
        image: jhispter4mono
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhispter4mono-postgresql:5432/jhispter4mono
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhispter4mono-postgresql:
        extends:
            file: postgresql.yml
            service: jhispter4mono-postgresql
